In [64]:
import pandas as pd
import numpy as np

In [65]:
dataset=pd.read_csv('/content/cars.csv')

In [66]:
dataset.head()

mpg   cylinders  cubicinches  ...   time-to-60  year     brand
0  14.0         8.0          350  ...           12  1972       US.
1  31.9         4.0           89  ...           14  1980   Europe.
2  17.0         8.0          302  ...           11  1971       US.
3  15.0         8.0          NaN  ...           10  1971       US.
4  30.5         4.0           98  ...           17  1978       US.

[5 rows x 8 columns]

In [67]:
dataset.isnull().sum()

mpg             0
 cylinders      1
 cubicinches    1
 hp             1
 weightlbs      0
 time-to-60     0
 year           0
 brand          0
dtype: int64

In [68]:
x=dataset.iloc[:,:-1].values

In [69]:
x

array([[14.0, 8.0, '350', ..., '4209', 12, 1972],
       [31.9, 4.0, '89', ..., '1925', 14, 1980],
       [17.0, 8.0, '302', ..., '3333', 11, 1971],
       ...,
       [22.0, 6.0, '232', ..., '2835', 15, 1983],
       [18.0, 6.0, '232', ..., '3288', 16, 1972],
       [22.0, 6.0, '250', ..., '3353', 15, 1977]], dtype=object)

In [70]:
y=dataset.iloc[:,7:].values

In [71]:
y

array([[' US.'],
       [' Europe.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' Europe.'],
       [' Japan.'],
       [' Japan.'],
       [' Europe.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' Japan.'],
       [' US.'],
       [' Japan.'],
       [' Europe.'],
       [' Japan.'],
       [' Europe.'],
       [' US.'],
       [' US.'],
       [' Japan.'],
       [' Japan.'],
       [' Japan.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' Japan.'],
       [' US.'],
       [' Japan.'],
       [' US.'],
       [' Japan.'],
       [' US.'],
       [' Europe.'],
       [' Japan.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' Japan.'],
       [' US.'],
       [' US.'],
       [' Europe.'],
       [' US.'],
       [' US.'],
       [' Europe.'],
       [' US.'],
       [' Europe.'],
       

In [72]:
from sklearn.impute import SimpleImputer

In [73]:
imp=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
x[:,1:6]=imp.fit_transform(x[:,1:6])

In [74]:
x

array([[14.0, 8.0, '350', ..., '4209', 12, 1972],
       [31.9, 4.0, '89', ..., '1925', 14, 1980],
       [17.0, 8.0, '302', ..., '3333', 11, 1971],
       ...,
       [22.0, 6.0, '232', ..., '2835', 15, 1983],
       [18.0, 6.0, '232', ..., '3288', 16, 1972],
       [22.0, 6.0, '250', ..., '3353', 15, 1977]], dtype=object)

In [47]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
x[:,0]=LE.fit_transform(x[:,0])

In [48]:
x

array([[4, 8.0, '350', ..., '4209', 12, 1972],
       [69, 4.0, '89', ..., '1925', 14, 1980],
       [12, 8.0, '302', ..., '3333', 11, 1971],
       ...,
       [35, 6.0, '232', ..., '2835', 15, 1983],
       [16, 6.0, '232', ..., '3288', 16, 1972],
       [35, 6.0, '250', ..., '3353', 15, 1977]], dtype=object)

In [49]:
y

array([[' US.'],
       [' Europe.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' Europe.'],
       [' Japan.'],
       [' Japan.'],
       [' Europe.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' Japan.'],
       [' US.'],
       [' Japan.'],
       [' Europe.'],
       [' Japan.'],
       [' Europe.'],
       [' US.'],
       [' US.'],
       [' Japan.'],
       [' Japan.'],
       [' Japan.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' Japan.'],
       [' US.'],
       [' Japan.'],
       [' US.'],
       [' Japan.'],
       [' US.'],
       [' Europe.'],
       [' Japan.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' US.'],
       [' Japan.'],
       [' US.'],
       [' US.'],
       [' Europe.'],
       [' US.'],
       [' US.'],
       [' Europe.'],
       [' US.'],
       [' Europe.'],
       

In [50]:
y=LE.fit_transform(y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [51]:
y

array([2, 0, 2, 2, 2, 2, 2, 2, 0, 1, 1, 0, 2, 2, 2, 2, 1, 2, 1, 0, 1, 0,
       2, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 0, 1, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 1, 2, 0, 2, 2, 1, 1, 1, 2, 2,
       0, 1, 0, 2, 2, 2, 1, 1, 0, 2, 2, 1, 0, 1, 2, 2, 2, 0, 0, 1, 2, 2,
       2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 0, 0, 2,
       1, 0, 2, 1, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 2, 2, 0, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 0, 2, 1, 1, 1, 2, 0, 2, 2, 2, 2, 1, 1, 2, 2,
       0, 2, 1, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0,
       2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0,
       0, 1, 0, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 0, 2, 1, 1, 2, 2, 2,
       2, 0, 2, 0, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 0, 1, 2, 2, 0, 0, 2, 2, 1, 2, 1, 2, 2, 2])